/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 01:42:41 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CalculadoraCusto_ESTest extends CalculadoraCusto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CalculadoraCusto calculadoraCusto0 = new CalculadoraCusto();
      double double0 = calculadoraCusto0.calcularFrete(9.769180414482, false);
      assertEquals(48.84590207241, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CalculadoraCusto calculadoraCusto0 = new CalculadoraCusto();
      // Undeclared exception!
      try { 
        calculadoraCusto0.calcularFrete(0.0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Peso invalido
         //
         verifyException("CalculadoraCusto", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CalculadoraCusto calculadoraCusto0 = new CalculadoraCusto();
      double double0 = calculadoraCusto0.calcularFrete(68.84590207241, false);
      assertEquals(309.806559325845, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CalculadoraCusto calculadoraCusto0 = new CalculadoraCusto();
      double double0 = calculadoraCusto0.calcularFrete(9.769180414482, true);
      assertEquals(68.84590207241, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CalculadoraCusto calculadoraCusto0 = new CalculadoraCusto();
      // Undeclared exception!
      try { 
        calculadoraCusto0.calcularFrete((-3000.4898614), true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Peso invalido
         //
         verifyException("CalculadoraCusto", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CalculadoraCusto calculadoraCusto0 = new CalculadoraCusto();
      double double0 = calculadoraCusto0.calcularFrete(10.0, false);
      assertEquals(50.0, double0, 0.01);
  }
}
